const fs=require('fs'),path=require('path'),http=require('http'),{URL}=require('url');
const{Client}=require('whatsapp-web.js');
const{StudentStore}=require('./lib/student-store');
const{recognizeImage,matchRules,sha256}=require('./lib/ocr-service');
const ROOT=__dirname,FILE=path.join(ROOT,'verification-config.json'),HTML=path.join(ROOT,'dashboard-v2.html');
const defaults={enabled:true,autoApprove:true,dryRun:true,minConfidence:55,rules:[],logs:[]};
let cfg=(()=>{try{return{...defaults,...JSON.parse(fs.readFileSync(FILE,'utf8'))}}catch{return{...defaults}}})();
const save=()=>fs.writeFileSync(FILE,JSON.stringify(cfg,null,2));
const store=new StudentStore(ROOT),groups=new Map();
const sid=v=>typeof v==='string'?v:v?._serialized||v?.$1||v?.user||'';
const key=v=>String(sid(v)).replace(/\D/g,'');
const rid=r=>sid(r?.id)||sid(r?.requesterId)||sid(r?.requester);
function log(action,details){cfg.logs.push({at:new Date().toISOString(),action,details:String(details||'')});cfg.logs=cfg.logs.slice(-200);save();console.log(`[student-gate] ${action}: ${details}`)}
async function group(client,id){try{const g=await client.getChatById(id);return g?.isGroup?g:null}catch(e){log('group_error',e.message);return null}}
async function approve(client,row){const g=await group(client,row.matched_group_id);if(!g)return{ok:false,reason:'تعذر تحميل الجروب'};const request=(await g.getGroupMembershipRequests()).find(x=>key(rid(x))===key(row.sender_id));if(!request)return{ok:false,reason:'لا يوجد طلب انضمام مطابق للرقم'};if(cfg.dryRun)return{ok:false,reason:'Dry-run مفعّل'};await g.approveGroupMembershipRequests({requesterIds:rid(request)});return{ok:true,reason:'تم قبول طلب الانضمام'}}
async function image(client,msg){if(!cfg.enabled||String(msg.from).endsWith('@g.us')||!msg.hasMedia)return;const media=await msg.downloadMedia();if(!media?.mimetype?.startsWith('image/'))return;await msg.reply('استلمت الصورة، جاري قراءتها محليًا…').catch(()=>{});const buffer=Buffer.from(media.data,'base64'),hash=sha256(buffer),dup=store.findDuplicate(hash,msg.from);if(dup){const id=store.insert({senderId:msg.from,senderNumber:key(msg.from),fileHash:hash,mimeType:media.mimetype,status:'review',decisionReason:`صورة مكررة من سجل ${dup.id}`});return msg.reply(`الصورة تحتاج مراجعة. رقم العملية ${id}`).catch(()=>{})}try{const ocr=await recognizeImage(buffer),matches=matchRules(ocr.normalizedText,cfg.rules);let status='review',reason='لا توجد كلمة مطابقة',match=null;if(ocr.confidence<cfg.minConfidence)reason=`ثقة منخفضة ${ocr.confidence.toFixed(1)}%`;else if(matches.length>1)reason='تطابق أكثر من جروب';else if(matches.length===1){match=matches[0];status='verified';reason='تطابق واضح'}const id=store.insert({senderId:msg.from,senderNumber:key(msg.from),fileHash:hash,mimeType:media.mimetype,extractedText:ocr.text,confidence:ocr.confidence,matchedRuleId:match?.rule.id,matchedGroupId:match?.rule.groupId,matchedKeyword:match?.keyword,status,decisionReason:reason});if(status==='verified'&&cfg.autoApprove){const d=await approve(client,store.get(id));store.updateDecision(id,d.ok?'approved':'review',d.reason);await msg.reply(d.ok?`تم قبول طلبك في ${match.rule.groupName||'الجروب'}.`:`تم التحقق لكن ${d.reason}. رقم العملية ${id}`).catch(()=>{})}else await msg.reply(`تمت القراءة وتحتاج مراجعة. رقم العملية ${id}`).catch(()=>{});log('ocr',`#${id} ${status}`)}catch(e){const id=store.insert({senderId:msg.from,senderNumber:key(msg.from),fileHash:hash,mimeType:media.mimetype,status:'failed',decisionReason:e.message});log('ocr_failed',`#${id} ${e.message}`)}}
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data))}
function body(req){return new Promise((ok,bad)=>{let s='';req.on('data',c=>s+=c);req.on('end',()=>{try{ok(s?JSON.parse(s):{})}catch{bad(Error('JSON غير صالح'))}});req.on('error',bad)})}
function serve(client){http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://127.0.0.1');if(req.method==='GET'&&u.pathname==='/'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});return res.end(fs.readFileSync(HTML))}if(req.method==='GET'&&u.pathname==='/api/status')return json(res,200,{ready:!!client.info?.wid,config:cfg,stats:store.stats()});if(req.method==='GET'&&u.pathname==='/api/groups')return json(res,200,{groups:[...groups.values()]});if(req.method==='GET'&&u.pathname==='/api/records')return json(res,200,{records:store.list({status:u.searchParams.get('status'),limit:300})});if(req.method==='GET'&&u.pathname==='/api/export'){const file=store.exportExcel();res.writeHead(200,{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':`attachment; filename=${path.basename(file)}`});return fs.createReadStream(file).pipe(res)}if(req.method==='POST'&&u.pathname==='/api/action'){const d=await body(req);if(d.action==='settings'){cfg={...cfg,...d.settings};save()}else if(d.action==='saveRule'){const r={...d.rule,id:d.rule.id||`rule-${Date.now()}`,enabled:true,keywords:(d.rule.keywords||[]).filter(Boolean)};if(!r.groupId||!r.keywords.length)throw Error('اختر الجروب واكتب الكلمات');const i=cfg.rules.findIndex(x=>x.id===r.id);i<0?cfg.rules.push(r):cfg.rules[i]=r;save()}else if(d.action==='deleteRule'){cfg.rules=cfg.rules.filter(x=>x.id!==d.id);save()}else if(d.action==='review'){const row=store.get(d.id);if(d.decision==='approve'){const a=await approve(client,row);store.updateDecision(d.id,a.ok?'approved':'review',a.reason)}else store.updateDecision(d.id,'rejected','رفض يدوي')}return json(res,200,{message:'تم الحفظ'})}return json(res,404,{error:'Not found'})}catch(e){json(res,500,{error:e.message})}}).listen(3001,'127.0.0.1',()=>console.log('Student Gate: http://127.0.0.1:3001'))}
function install(client){if(client.__studentGate)return;client.__studentGate=true;client.on('message',m=>{if(String(m.from).endsWith('@g.us'))groups.set(m.from,{id:m.from,name:groups.get(m.from)?.name||m.from});image(client,m).catch(e=>log('message_error',e.message))});client.on('ready',()=>client.getChats().then(chats=>chats.filter(c=>c.isGroup).forEach(c=>groups.set(sid(c.id),{id:sid(c.id),name:c.name}))).catch(()=>{}));serve(client)}
const init=Client.prototype.initialize;Client.prototype.initialize=function(...args){install(this);return init.apply(this,args)};
