const fs=require('fs'),path=require('path'),http=require('http'),{URL}=require('url'),{Client}=require('whatsapp-web.js');
const{StudentStore}=require('./lib/student-store');const{recognizeImage,matchRules,sha256}=require('./lib/ocr-service');
const ROOT=__dirname,CONFIG_FILE=path.join(ROOT,'verification-config.json'),MAIN_CONFIG_FILE=path.join(ROOT,'config.json'),DASHBOARD_FILE=path.join(ROOT,'dashboard-v2.html'),defaults={enabled:true,autoApprove:true,dryRun:true,minConfidence:55,maxQueue:200,rules:[],logs:[]};
let config=(()=>{try{return{...defaults,...JSON.parse(fs.readFileSync(CONFIG_FILE,'utf8'))};}catch{return{...defaults};}})();
const save=()=>fs.writeFileSync(CONFIG_FILE,JSON.stringify(config,null,2)),store=new StudentStore(ROOT),groups=new Map(),processed=new Set(),queue=[];let queueRunning=false;
const sid=v=>typeof v==='string'?v:v?._serialized||v?.$1||v?.user||'',key=v=>String(sid(v)).replace(/\D/g,''),requestId=r=>sid(r?.id)||sid(r?.requesterId)||sid(r?.requester),isPrivateUser=id=>/@(c\.us|lid)$/.test(String(id||''));
function log(action,details){config.logs.push({at:new Date().toISOString(),action,details:String(details||'')});config.logs=config.logs.slice(-300);save();console.log(`[student-gate] ${action}: ${details}`);}
function ownerChatId(){let ownerNumber=config.ownerNumber||'201040224684';try{const mainConfig=JSON.parse(fs.readFileSync(MAIN_CONFIG_FILE,'utf8'));ownerNumber=mainConfig.ownerNumber||ownerNumber;}catch{}const number=String(ownerNumber).replace(/\D/g,'');return number?`${number}@c.us`:null;}
async function notifyOwnerForReview(client,media,row){const ownerId=ownerChatId();if(!ownerId||!row)return;const caption=[`⚠️ بطاقة تحتاج مراجعة — #${row.id}`,`السبب: ${row.decision_reason||'مراجعة يدوية'}`,`رقم واتساب: ${row.sender_number||row.sender_id||'غير معروف'}`,`اسم الطالب: ${row.student_name||'غير واضح'}`,`الرقم القومي: ${row.national_id||'غير واضح'}`,`كود الطالب: ${row.student_code||'غير واضح'}`,`البرنامج: ${row.program||'غير واضح'}`,`المستوى: ${row.level||'غير واضح'}`,`الكلية: ${row.college||'غير واضحة'}`,`الفرقة: ${row.cohort||'غير واضحة'}`,`العام الجامعي: ${row.academic_year||'غير واضح'}`,`الكلمة المطابقة: ${row.matched_keyword||'لا توجد'}`,'','راجع العملية من لوحة Student Gate على جهاز البوت.'].join('\n');try{if(media)await client.sendMessage(ownerId,media,{caption});else await client.sendMessage(ownerId,caption);log('review_notified',`#${row.id} -> ${ownerId}`);}catch(error){log('review_notify_failed',`#${row.id}: ${error.message}`);}}
async function getGroup(client,id){try{const chat=await client.getChatById(id);return chat?.isGroup?chat:null;}catch(error){log('group_error',`${id}: ${error.message}`);return null;}}
async function approve(client,row){const group=await getGroup(client,row.matched_group_id);if(!group)return{ok:false,reason:'تعذر تحميل الجروب'};const request=(await group.getGroupMembershipRequests()).find(item=>key(requestId(item))===key(row.sender_id));if(!request)return{ok:false,reason:'لا يوجد طلب انضمام مطابق لنفس الرقم'};if(config.dryRun)return{ok:false,reason:'Dry-run مفعّل'};await group.approveGroupMembershipRequests({requesterIds:requestId(request)});return{ok:true,reason:'تم قبول طلب الانضمام'};}
async function processPrivateImage(client,msg){const media=await msg.downloadMedia();if(!media?.mimetype?.startsWith('image/'))return;const buffer=Buffer.from(media.data,'base64'),hash=sha256(buffer),duplicate=store.findDuplicate(hash,msg.from);if(duplicate){const id=store.insert({senderId:msg.from,senderNumber:key(msg.from),fileHash:hash,mimeType:media.mimetype,status:'review',decisionReason:`الصورة مستخدمة بواسطة رقم آخر في سجل ${duplicate.id}`});await msg.reply(`الصورة مكررة وتحتاج مراجعة. رقم العملية: ${id}`).catch(()=>{});await notifyOwnerForReview(client,media,store.get(id));return;}try{const ocr=await recognizeImage(buffer),matches=matchRules(ocr.normalizedText,config.rules);let status='review',reason='لا توجد قاعدة جروب مطابقة',match=null;if(ocr.confidence<Number(config.minConfidence||55))reason=`جودة القراءة منخفضة (${ocr.confidence.toFixed(1)}%)`;else if(matches.length>1)reason='البطاقة تطابق أكثر من جروب';else if(matches.length===1){match=matches[0];status='verified';reason='تم التحقق من البطاقة';}const f=ocr.fields||{},id=store.insert({senderId:msg.from,senderNumber:key(msg.from),fileHash:hash,mimeType:media.mimetype,extractedText:ocr.text,confidence:ocr.confidence,studentName:f.studentName,nationalId:f.nationalId,college:f.college,cohort:f.cohort,academicYear:f.academicYear,studentCode:f.studentCode,program:f.program,level:f.level,matchedRuleId:match?.rule.id,matchedGroupId:match?.rule.groupId,matchedKeyword:match?.keyword,status,decisionReason:reason});if(status==='verified'&&config.autoApprove){const decision=await approve(client,store.get(id));store.updateDecision(id,decision.ok?'approved':'review',decision.reason);await msg.reply(decision.ok?`تم التحقق وقبول طلبك في ${match.rule.groupName||'الجروب'}.`:`تم استخراج بياناتك لكن ${decision.reason}. رقم العملية: ${id}`).catch(()=>{});if(!decision.ok)await notifyOwnerForReview(client,media,store.get(id));}else{if(status==='verified')store.updateDecision(id,'review','بانتظار موافقة يدوية');await msg.reply(`تم استخراج بيانات البطاقة وإضافتها للمراجعة. رقم العملية: ${id}`).catch(()=>{});await notifyOwnerForReview(client,media,store.get(id));}log('ocr',`#${id} ${store.get(id).status} ${f.studentName||''} ${f.college||''} ${f.program||''}`);}catch(error){const id=store.insert({senderId:msg.from,senderNumber:key(msg.from),fileHash:hash,mimeType:media.mimetype,status:'failed',decisionReason:error.message});log('ocr_failed',`#${id} ${error.message}`);await msg.reply(`تعذر قراءة الصورة الآن وتم تسجيلها للمراجعة. رقم العملية: ${id}`).catch(()=>{});await notifyOwnerForReview(client,media,store.get(id));}}
function enqueue(client,msg){if(queue.length>=Number(config.maxQueue||200)){msg.reply('يوجد ضغط كبير حاليًا. حاول إرسال الصورة مرة أخرى بعد دقائق.').catch(()=>{});return;}queue.push({client,msg});const position=queue.length+(queueRunning?1:0);msg.reply(position>1?`تم استلام الصورة. ترتيبك في المعالجة: ${position}`:'تم استلام الصورة وجاري قراءة البيانات محليًا…').catch(()=>{});runQueue();}
async function runQueue(){if(queueRunning)return;queueRunning=true;while(queue.length){const job=queue.shift();await processPrivateImage(job.client,job.msg).catch(error=>log('queue_error',error.message));}queueRunning=false;}
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));}
function readBody(req){return new Promise((resolve,reject)=>{let raw='';req.on('data',c=>raw+=c);req.on('end',()=>{try{resolve(raw?JSON.parse(raw):{});}catch{reject(Error('JSON غير صالح'));}});req.on('error',reject);});}
function serve(client){http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://127.0.0.1');if(req.method==='GET'&&url.pathname==='/'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});return res.end(fs.readFileSync(DASHBOARD_FILE));}if(req.method==='GET'&&url.pathname==='/api/status')return json(res,200,{ready:!!client.info?.wid,config,stats:{...store.stats(),queued:queue.length+(queueRunning?1:0)}});if(req.method==='GET'&&url.pathname==='/api/groups')return json(res,200,{groups:[...groups.values()]});if(req.method==='GET'&&url.pathname==='/api/records')return json(res,200,{records:store.list({status:url.searchParams.get('status'),limit:500})});if(req.method==='GET'&&url.pathname==='/api/export'){const file=store.exportExcel();res.writeHead(200,{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':`attachment; filename=${path.basename(file)}`});return fs.createReadStream(file).pipe(res);}if(req.method==='POST'&&url.pathname==='/api/action'){const data=await readBody(req);if(data.action==='settings'){config={...config,...data.settings};save();}else if(data.action==='saveRule'){const rule={...data.rule,id:data.rule.id||`rule-${Date.now()}`,enabled:true,keywords:(data.rule.keywords||[]).filter(Boolean)};if(!rule.groupId||!rule.keywords.length)throw Error('اختر الجروب واكتب الكلمات');const index=config.rules.findIndex(x=>x.id===rule.id);index<0?config.rules.push(rule):config.rules[index]=rule;save();}else if(data.action==='deleteRule'){config.rules=config.rules.filter(x=>x.id!==data.id);save();}else if(data.action==='review'){const row=store.get(data.id);if(data.decision==='approve'){const decision=await approve(client,row);store.updateDecision(data.id,decision.ok?'approved':'review',decision.reason);}else store.updateDecision(data.id,'rejected','رفض يدوي');}return json(res,200,{message:'تم الحفظ'});}return json(res,404,{error:'Not found'});}catch(error){json(res,500,{error:error.message});}}).listen(3001,'127.0.0.1',()=>console.log('Student Gate: http://127.0.0.1:3001'));}
function install(client){if(client.__studentGateV2)return;client.__studentGateV2=true;client.on('message',msg=>{const id=sid(msg.id);if(id&&processed.has(id))return;if(id){processed.add(id);if(processed.size>5000)processed.delete(processed.values().next().value);}if(String(msg.from).endsWith('@g.us')){groups.set(msg.from,{id:msg.from,name:groups.get(msg.from)?.name||msg.from});return;}if(!config.enabled||!isPrivateUser(msg.from)||!msg.hasMedia)return;enqueue(client,msg);});client.on('ready',()=>client.getChats().then(chats=>chats.filter(c=>c.isGroup).forEach(c=>groups.set(sid(c.id),{id:sid(c.id),name:c.name}))).catch(()=>{}));serve(client);}
const initialize=Client.prototype.initialize;Client.prototype.initialize=function(...args){install(this);return initialize.apply(this,args);};
