const crypto = require('crypto');
const { createWorker } = require('tesseract.js');
let workerPromise;
let lastProgress = -10;
function normalizeText(value) { return String(value || '').normalize('NFKC').replace(/[أإآ]/g, 'ا').replace(/ة/g, 'ه').replace(/ى/g, 'ي').replace(/[ـً-ٟ]/g, '').replace(/\s+/g, ' ').trim().toLowerCase(); }
function toEnglishDigits(value) { const arabic='٠١٢٣٤٥٦٧٨٩',persian='۰۱۲۳۴۵۶۷۸۹'; return String(value||'').replace(/[٠-٩]/g,d=>String(arabic.indexOf(d))).replace(/[۰-۹]/g,d=>String(persian.indexOf(d))); }
function cleanValue(value) { return String(value||'').replace(/[‎‏‪-‮]/g,'').replace(/^[^\p{L}\p{N}]+/u,'').replace(/\s+/g,' ').trim(); }
function nextLine(lines, pattern) { const index=lines.findIndex(line=>pattern.test(normalizeText(line))); if(index<0)return''; for(let i=index+1;i<Math.min(lines.length,index+4);i++){const value=cleanValue(lines[i]);if(value&&!/^(الرقم القومي|الكليه|الفرقه|العام الجامعي|اسم الطالب)$/i.test(normalizeText(value)))return value;} return''; }
function labelValue(lines,pattern){for(let i=0;i<lines.length;i++){if(!pattern.test(normalizeText(lines[i])))continue;const raw=cleanValue(lines[i]),parts=raw.split(/[:：]/);if(parts.length>1){const rest=cleanValue(parts.slice(1).join(':'));if(rest)return rest;}for(let j=i+1;j<Math.min(lines.length,i+4);j++){const v=cleanValue(lines[j]);if(v)return v;}return'';}return'';}
function parseStudentCard(text) { const lines=String(text||'').split(/\r?\n/).map(cleanValue).filter(Boolean),digits=toEnglishDigits(text).replace(/[^0-9]/g,' '),nationalId=(digits.match(/(?:^|\s)(\d{14})(?:\s|$)/)||[])[1]||''; let studentName=nextLine(lines,/اسم الطالب/)||labelValue(lines,/(^|\s)الاسم(\s|:|$)/); studentName=studentName.replace(/[^\p{Script=Arabic}\s'-]/gu,' ').replace(/\s+/g,' ').trim(); const college=nextLine(lines,/^الكليه$|^كليه/)||labelValue(lines,/(^|\s)الكليه(\s|:|$)/),cohort=nextLine(lines,/^الفرقه$/)||labelValue(lines,/(^|\s)الفرقه(\s|:|$)/),yearMatch=toEnglishDigits(text).match(/20\d{2}\s*[/\\-]\s*20\d{2}/),program=labelValue(lines,/(^|\s)البرنامج(\s|:|$)/),level=labelValue(lines,/(^|\s)المستوي(\s|:|$)/); let studentCode=toEnglishDigits(labelValue(lines,/(^|\s)الكود(\s|:|$)/)).replace(/[^0-9]/g,''); if(!studentCode){const m=digits.match(/(?:^|\s)(\d{6,12})(?:\s|$)/);studentCode=m?m[1]:'';} return{studentName,nationalId,college:cleanValue(college),cohort:cleanValue(cohort),academicYear:yearMatch?yearMatch[0].replace(/\s/g,'').replace(/[\\-]/g,'/'):'',studentCode,program:cleanValue(program),level:cleanValue(level)}; }
async function getWorker(){if(!workerPromise)workerPromise=createWorker('ara+eng',1,{logger:event=>{if(event.status!=='recognizing text'||!Number.isFinite(event.progress))return;const percent=Math.round(event.progress*100);if(percent===100||percent>=lastProgress+10){lastProgress=percent;console.log(`[ocr] ${percent}%`);}}});return workerPromise;}
async function recognizeImage(buffer){lastProgress=-10;const worker=await getWorker(),result=await worker.recognize(buffer),text=String(result.data.text||'').trim();return{text,normalizedText:normalizeText(text),confidence:Number(result.data.confidence||0),fields:parseStudentCard(text)};}
function sha256(buffer){return crypto.createHash('sha256').update(buffer).digest('hex');}
function matchRules(text,rules=[]){const normalized=normalizeText(text),compact=normalized.replace(/\s+/g,''),matches=[];for(const rule of rules.filter(item=>item&&item.enabled!==false&&item.groupId))for(const keyword of Array.isArray(rule.keywords)?rule.keywords:[]){const normalizedKeyword=normalizeText(keyword),compactKeyword=normalizedKeyword.replace(/\s+/g,'');if(normalizedKeyword&&(normalized.includes(normalizedKeyword)||(compactKeyword&&compact.includes(compactKeyword)))){matches.push({rule,keyword});break;}}return matches;}
module.exports={recognizeImage,matchRules,normalizeText,parseStudentCard,sha256};
